### ISSUE TITLE
[Question] 과제 2. 질문입니다

### ISSUE THREAD

**Issue by ssu-uky** [lordmyshepherd-edu/wanted-pre-onboardung-backend-selection-assignment#4]
과제 2. 사용자 로그인 엔드포인트
사용자가 올바른 이메일과 비밀번호를 제공하면, 사용자 인증을 거친 후에 JWT(JSON Web Token)를 생성하여 사용자에게 반환하도록 해주세요.
과제 1과 마찬가지로 **_회원가입 엔드포인트에 이메일과 비밀번호의 유효성 검사기능을 구현해주세요._**

라고 되어 있는데,

마지막 줄에
회원가입 엔드포인트가 아닌 로그인 엔드포인트에 이메일과 비밀번호의 유효성 검사 기능을 구현해 주세요. 일까요...?

회원가입, 로그인 둘 다 유효성 검사 기능을 해야 하는 건지, 회원가입 때만 유효성 검사를 하면 되는 건지 여쭤봅니다.

**Comment by honki12345** [comment]
저도 같은 의문점이 있어서 이 thread follow 하고 있었는데 issue close 됐네요
혹시 답을 얻으셨나요...?

**Comment by ssu-uky** [comment]
> 저도 같은 의문점이 있어서 이 thread follow 하고 있었는데 issue close 됐네요 혹시 답을 얻으셨나요...?

앗 아뇨... 답을 안 주셔서 이 부분은 상관없는 줄 알고 close 한 거였습니다.
저도 아직 궁금합니다 ㅠㅠ..
다시 오픈하였습니다 :)
